# Generated by Django 5.0.3 on 2024-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0005_remove_campgrounds_image_alter_campgrounds_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campgrounds',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='campgrounds',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='campgrounds',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
