# Generated by Django 5.0.3 on 2024-03-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0007_remove_campgrounds_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campgrounds',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
