# Generated by Django 5.0.3 on 2024-03-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0008_campgrounds_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgrounds',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campgrounds',
            name='start_date',
            field=models.DateField(),
        ),
    ]
