# Generated by Django 5.0.3 on 2024-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0009_alter_campgrounds_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgrounds',
            name='images',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
