# Generated by Django 5.0.3 on 2024-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0010_alter_campgrounds_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgrounds',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
