# Generated by Django 5.0.3 on 2024-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0011_alter_campgrounds_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campgrounds',
            name='images',
        ),
        migrations.AddField(
            model_name='campgrounds',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
