# Generated by Django 5.0.3 on 2024-03-20 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0012_remove_campgrounds_images_campgrounds_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_camps_available', models.IntegerField()),
                ('campground_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campgrounds.campgrounds')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nb_persons', models.IntegerField()),
                ('f_cancel', models.BooleanField()),
                ('f_confirmed', models.BooleanField()),
                ('campground_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campgrounds.campgrounds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
