# Generated by Django 5.0.3 on 2024-03-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0013_availability_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgrounds',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('NR', 'Not rated')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('NR', 'Not rated')], max_length=2, null=True),
        ),
    ]
