# Generated by Django 5.0.3 on 2024-03-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0016_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgrounds',
            name='rating',
            field=models.CharField(choices=[('NR', 'Not Rated'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='NR', max_length=10),
        ),
    ]
