# Generated by Django 5.0.3 on 2024-03-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0020_remove_campgrounds_rating_campgrounds_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('NR', 'not rated'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='NR', max_length=10),
        ),
    ]
