# Generated by Django 5.0.3 on 2024-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0024_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgrounds',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
